In [ ]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from llm.llm_models import headline_rating, relevance_extractor 
import time
healthcare = ['ISRG', 'LLY', 'IDXX', 'BSX', 'EW', 'DHR', 'SYK', 'CI', 'BMY', 'CVS']
energy = ['WMB', 'KMI', 'OKE', 'OXY', 'CVX', 'XOM', 'PSX', 'EOG', 'FANG', 'SLB']
technology = ['PLTR', 'CRWD', 'NOW', 'FICO', 'PANW', 'ANET', 'CDNS', 'QCOM', 'DELL', 'MU']
stocks = {'healthcare': healthcare, 'energy': energy, 'technology': technology}
path = 'data.csv'
data = pd.read_csv(path)
data['date'] = pd.to_datetime(data['date']).dt.day
date_range = data['date'].unique()
final_data = []
for days in date_range:
    data_splice = data[data['date'] == days]
    for sector in list(stocks.keys()):
        relevance_list = []
        for x in data_splice['headline']:
            relevance_list += [relevance_extractor(x, sector)]
            time.sleep(1)
        headlines = data_splice[relevance_list]['headline'].tolist()
        for stock in stocks[sector]:
            rating = headline_rating(data_splice['headline'][relevance_list].tolist(), stock)
            final_data.append([stock, days, rating])
            time.sleep(1)
final_df = pd.DataFrame(final_data, columns=['stock', 'date', 'rating'])
final_df

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

    stock  date  rating
0    ISRG    22      -3
1     LLY    22      -3
2    IDXX    22      -2
3     BSX    22      -3
4      EW    22      -3
..    ...   ...     ...
235  ANET    31      -4
236  CDNS    31      -3
237  QCOM    31      -3
238  DELL    31      -3
239    MU    31      -2

[240 rows x 3 columns]

Output of rating_pipeline is to be used for the day after date.

In [ ]:
%load_ext autoreload
%autoreload 2
from rating_pipeline import rating_pipeline
healthcare = ['ISRG', 'LLY', 'IDXX', 'BSX', 'EW', 'DHR', 'SYK', 'CI', 'BMY', 'CVS']
energy = ['WMB', 'KMI', 'OKE', 'OXY', 'CVX', 'XOM', 'PSX', 'EOG', 'FANG', 'SLB']
technology = ['PLTR', 'CRWD', 'NOW', 'FICO', 'PANW', 'ANET', 'CDNS', 'QCOM', 'DELL', 'MU']
stocks = {'healthcare': healthcare, 'energy': energy, 'technology': technology}
rating_pipeline('data.csv', stocks, "predictions.csv")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
20
2
2
1

   stock       date  rating
0   ISRG 2025-01-22      -3
1    LLY 2025-01-22      -4
2   IDXX 2025-01-22      -3
3    BSX 2025-01-22      -4
4     EW 2025-01-22      -3
5    DHR 2025-01-22      -4
6    SYK 2025-01-22      -4
7     CI 2025-01-22      -4
8    BMY 2025-01-22      -3
9    CVS 2025-01-22      -3
10   WMB 2025-01-22      -3
11   KMI 2025-01-22      -3
12   OKE 2025-01-22      -3
13   OXY 2025-01-22      -2
14   CVX 2025-01-22      -3
15   XOM 2025-01-22      -3
16   PSX 2025-01-22      -3
17   EOG 2025-01-22      -3
18  FANG 2025-01-22      -3
19   SLB 2025-01-22      -3
20  PLTR 2025-01-22      -3
21  CRWD 2025-01-22      -3
22   NOW 2025-01-22      -3
23  FICO 2025-01-22      -4
24  PANW 2025-01-22      -3
25  ANET 2025-01-22      -3
26  CDNS 2025-01-22      -3
27  QCOM 2025-01-22      -3
28  DELL 2025-01-22      -3
29    MU 2025-01-22      -3